### ISSUE TITLE
Request to use figures in report

### ISSUE THREAD

**Issue by n33lkanth** [fvisin/thesis#1]
Dear @fvisin, I recently came across your doctoral thesis and I found it very useful. I want to use a few of the figures from your thesis in my report and would like to request your permission for the same. Kindly let me know if you permit me to use the figures and if yes then how should I add references (I mean any paper published which I can add as a reference in my report)for these figures in my report.

Best Regards

**Comment by fvisin** [comment]
Dear @n33lkanth, 

Thank you for your interest, I am glad you found my thesis useful! And of course, feel free to use the figures with attribution to the original paper, where possible, or to the thesis itself in lack of a better reference ("Deep recurrent neural networks for visual scene understanding").

Kind Regards

**Comment by n33lkanth** [comment]
Dear @fvisin,
Thank you very much for your consent.


Best Regards
